kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
    - hostPath: /tmp/kind-storage      # Your physical machine path
      containerPath: /mnt/data        # Path inside the kind node
  - role: worker
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
