FROM golang:alpine3.23 as builder

WORKDIR /src
# hadolint ignore=DL3018
RUN apk update && apk add --no-cache git make
# hadolint ignore=DL3003
RUN git clone https://github.com/seaweedfs/seaweedfs.git && \
    cd seaweedfs && git checkout 0e9f70215296cf5f3e85c1fbe8fe180939bfa0b3 && \
    cd /src/seaweedfs/weed && make install

FROM scratch
COPY --from=builder /go/bin/weed /weed
ENTRYPOINT ["/weed"]
